### ISSUE TITLE
[Request] Enable discussions

### ISSUE THREAD

**Issue by IvanGodinez21** [reZach/secure-electron-template#100]
**Is your feature request related to a problem? Please describe.**
Isn't a problem

**Describe the solution you'd like**
It's hard to search for information about how to use this magnificent template, we need a site to communicate with each other to find solutions when we are stuck in a problem.

**Describe alternatives you've considered**
Enabling this option would be useful for many users who have questions (so they don't have to create issues).
![image](https://user-images.githubusercontent.com/45635827/145696606-d4bec596-0af7-4ee5-86ae-c62ce984e43e.png)

**Additional context**
I need help with something like everyone I guess, that is why I think that this is a great feature request

**Comment by reZach** [comment]
Thanks @IvanGodinez21, I'm familiar with the new feature but haven't decided to enable them yet. Were you able to see [the faq](https://github.com/reZach/secure-electron-template/blob/master/docs/faq.md) in the readme (or was it too buried)? Regardless, what's your question you'd like to see answered on the "Discussion" section?

**Comment by IvanGodinez21** [comment]
Thanks for the response @reZach. I want to add a package (node-localdb-modern) to one of the pages, for example, I'm using that package in "motd.jsx" but when I import it, the electron application gets stuck and doesn't start. I'm new using this template and using electron, am I missing something? (I tried using other packages and I get the same problem).

![image](https://user-images.githubusercontent.com/45635827/145735494-59b1be74-65c7-492f-b87a-932474d2fc47.png)

**Comment by reZach** [comment]
@IvanGodinez21 based on the [usage](https://github.com/carlos0202/node-localdb#useage) documentation, it would be my best guess that this code needs to be in **main.js**. _Generally_, when using this template - you have to put all of your file-access/database calls in this case in **main.js**, and then communicate back and forth from your renderer thread with IPC.

Let me know if that gives you enough to go off of.

**Comment by IvanGodinez21** [comment]
Oh ok, thanks @reZach, if I face a problem I tell you. If you want, you can close this issue
