### ISSUE TITLE
Incorrect setup for i18next

### ISSUE THREAD

**Issue by lukehaas** [reZach/secure-electron-template#101]
It looks like the way i18next is setup in this project is incorrect. When turning on the `debug` option in `app/localization/i18n.mainconfig.js` - errors are produced such as this one:
```
i18next::translator: key "About" for languages "en" won't get resolved as namespace "translation" was not yet loaded This means something IS WRONG in your setup. You access the t function before i18next.init / i18next.loadNamespace / i18next.changeLanguage was done. Wait for the callback or Promise to resolve before accessing it!!!
```

**Comment by reZach** [comment]
Thanks for reporting this @lukehaas. I've [pushed a fix](https://github.com/reZach/secure-electron-template/releases/tag/v16.0.1) that will resolve the error - can you let me know if this fixes the message for you?

**Comment by lukehaas** [comment]
Thanks @reZach, fix is good. 
However, there is a simpler way as the i18n object has the property `isInitialized` so there is no need to introduce your own variable to track this, just use `i18nextMainBackend.isInitialized`

**Comment by reZach** [comment]
Thanks @lukehaas, I've pushed [another update](https://github.com/reZach/secure-electron-template/releases/tag/v16.0.2) to use this property. Thanks for your help!
