### ISSUE TITLE
[Question] why is exposing ipcrenderer.send secure?

### ISSUE THREAD

**Issue by ofsaleem** [reZach/secure-electron-template#102]
I'm looking at [this page](https://github.com/reZach/secure-electron-template/blob/master/docs/newtoelectron.md) and I'm not understanding something. Why is it that 

```js
contextBridge.exposeInMainWorld(
    "api", {
        send: (channel, data) => {
            // whitelist channels
            let validChannels = ["toMain"];
            if (validChannels.includes(channel)) {
                ipcRenderer.send(channel, data);
            }
        }
);
```

is considered secure? In the Electron docs for [Context Isolation](https://www.electronjs.org/docs/v14-x-y/tutorial/context-isolation) they use the following as an example of bad code:

```js
// ❌ Bad code
contextBridge.exposeInMainWorld('myAPI', {
  send: ipcRenderer.send
})
```
with the explanation
> It directly exposes a powerful API without any kind of argument filtering. This would allow any website to send arbitrary IPC messages, which you do not want to be possible. The correct way to expose IPC-based APIs would instead be to provide one method per IPC message.

Now, I understand that the way your docs do it is slightly different as it requires a valid channel. But I don't really follow why that makes much of a difference, can't an attacker just see which channel is being used and use that one? And if that doesn't work because of xyz security feature, then why is the "bad code" example actually unsafe? 

Please help me understand the difference, and if possible add additional clarity to the section in that doc about `preload.js` to help others like me who _really_ struggle with the lack of examples and explanations about IPC stuff in Electron ❤️

Followup question would be, does this mean for any given Electron app, I can just expose send/receive/invoke/handle/on/etc like this, with one channel per function I need called, and never have to expose specific functions I've `require`'d in `main.js`? It would be pretty handy not having to essentially write a wrapper API for every individual function call I need to make that uses a Node feature or external library lol

**Comment by reZach** [comment]
Hi @ofsaleem,

Thanks for asking the question. I've [posted an update](https://github.com/reZach/secure-electron-template/blob/master/docs/newtoelectron.md#can-you-explain-what-these-channels-are-for) to that page, can you check it out to see if it answers your question? 

In short, yes - an attacker could see what channels are available to use. However, since the actual _use_ of the `require`'d module is in the **main.js** file (which the attacker couldn't change, spare decompiling and modifying the source code which at this point no security safeguard is going to work), they only have access to execute bad code on how locked-down your code in **main.js** is. If your code in **main.js** allows for arbitrary execution of methods, an attacker can figure out how to call a method that causes some damage. If your code in **main.js** only say allows for methods that are tied to your app, the worst they can do is possibly stop the app from working correctly, as opposed to making changes to an underlying OS.

You don't _necessarily_ have to create one channel per function, you could do a slightly easier implementation if you desire. Of course, you should be **careful** that you handle all edge cases when you do this or otherwise, you don't want to step into the line of calling methods dynamically.

**preload**
```javascript
const {
    contextBridge,
    ipcRenderer
} = require("electron");

// Expose protected methods that allow the renderer process to use
// the ipcRenderer without exposing the entire object
contextBridge.exposeInMainWorld(
    "api", {
        send: (channel, data) => {
            // whitelist channels
            let validChannels = ["toMain"];
            if (validChannels.includes(channel)) {
                ipcRenderer.send(channel, data);
            }
        },
        receive: (channel, func) => {
            let validChannels = ["fromMain"];
            if (validChannels.includes(channel)) {
                // Deliberately strip event as it includes `sender` 
                ipcRenderer.on(channel, (event, ...args) => func(...args));
            }
        }
    }
);
```

**main**
```javascript
const {
  app,
  BrowserWindow,
  ipcMain
} = require("electron");
const path = require("path");
const fs = require("fs");

// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let win;

async function createWindow() {

  // Create the browser window.
  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: false, // is default value after Electron v5
      contextIsolation: true, // protect against prototype pollution
      enableRemoteModule: false, // turn off remote
      preload: path.join(__dirname, "preload.js") // use a preload script
    }
  });

  // Load app
  win.loadFile(path.join(__dirname, "dist/index.html"));

  // rest of code..
}

app.on("ready", createWindow);

ipcMain.on("toMain", (event, args) => {

  if (args.payload.method === "read") {
    // fs .readFile
  } else if (args.payload.method === "write") {
    // fs .writeFile
  }

  // Send result back to renderer process
  win.webContents.send("fromMain", responseObj);
});
```

**index**
```html
<!doctype html>
<html lang="en-US">
<head>
    <meta charset="utf-8"/>
    <title>Title</title>
</head>
<body>
    <script>
        // Called when message received from main process
        window.api.receive("fromMain", (data) => {
            console.log(`Received ${data} from main process`);
        });

        // Send a message to the main process
        window.api.send("toMain", {
            payload: {
                method: "read"
            }
        });
    </script>
</body>
</html>
```

**Comment by ofsaleem** [comment]
Yes, ty, your reply and that update explains it clearly. In fact it doesn't seem much different than having a separate function for each channel, since you have access to the same methods either way. The way I was doing it:

```javascript
contextBridge.exposeInMainWorld(
  'ffbinaries', 
  {
    downloadFFBinaries: () => downloadFFBinaries()
  });
contextBridge.exposeInMainWorld(
  'ffmpeg',
  {
    renderWithVectorscope: (mp3path, imagepath) => renderWithVectorscope(mp3path, imagepath),
    renderWithWaveforms: (mp3path, imagepath, fixedImageWidth) => renderWithWaveforms(mp3path, imagepath, fixedImageWidth)
  }
);

const downloadFFBinaries = () => {
  return ipcRenderer.invoke('get-ffbinaries').then(result => {
    return result;
  }).catch(() => {
    console.error("Error determining platform");
  });
}

const renderWithVectorscope = (mp3path, imagepath) => {
  return ipcRenderer.invoke('ffmpeg-vectorscope', mp3path, imagepath).catch(() => {
    console.error("Error rendering output video file");
  });
}

const renderWithWaveforms = (mp3path, imagepath, fixedImageWidth) => {
  return ipcRenderer.invoke('ffmpeg-waveforms', mp3path, imagepath, fixedImageWidth).catch(() => {
    console.error("Error rendering output video file");
  });
}
```
all in `preload.js` so I had to write additional functions for every external call I had to make. Your method seems like way less effort. Thanks!!
