### ISSUE TITLE
Content security Policy not found

### ISSUE THREAD

**Issue by vpeace** [reZach/secure-electron-template#105]
Thanks for your repository it has been very helpful to me. I have only 1 doubt .I'm not able to find the code for Content security policy, if you could help me with that it would be great.
Thanks

**Comment by vpeace** [comment]
I got the data, it was present in the .js file sorry

**Comment by reZach** [comment]
Thanks @vpeace, yes the CSPs are defined in the webpack configs (ie. https://github.com/reZach/secure-electron-template/blob/master/webpack.development.js)
