### ISSUE TITLE
integrating react v18 be default

### ISSUE THREAD

**Issue by imyosh** [reZach/secure-electron-template#111]
I just discovered this template and I want to use it, but I noticed that this template uses React V17 and not V18, is there maybe a reason for not updating react version ? cuz React V18 came with nice updates

**Comment by reZach** [comment]
Thanks @imyosh, I've [pushed up some working changes](https://github.com/reZach/secure-electron-template/tree/react-v18-upgrade), but unfortunately it appears there are some issues between React & [react-i18next](https://github.com/i18next/react-i18next/). Do you have intuition to what the problem may be?

![image](https://user-images.githubusercontent.com/4740370/170178512-683768dd-aaeb-48ce-87a1-fa25e5d04308.png)

**Comment by reZach** [comment]
@imyosh The [latest release](https://github.com/reZach/secure-electron-template/releases/tag/v19.0.0) uses React v18. You should be good to go now - thanks for posting this issue.
