### ISSUE TITLE
NPM Audit Fix --Force Breaks Template

### ISSUE THREAD

**Issue by Zagunda** [reZach/secure-electron-template#114]
Using NPM Audit Fix --force causes the template to stay in 'Application is currently initializing...' state never loading. Many issues report with NPM Audit. Solution?

**Comment by reZach** [comment]
Thanks @Zagunda, I'd avoid running `npm audit fix --force` for now, the dependencies don't get auto-resolved nicely (the packages get seriously _downgraded_)... I would consider going to the [**nanoid**](https://www.npmjs.com/package/nanoid) / [**got**](https://www.npmjs.com/package/got) repositories for them to fix this issue downstream.

PS C:\Users\zachary\source\repos\secure-electron-template> npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating @doyensec/electronegativity to 1.7.0,which is a SemVer major change.
npm WARN audit Updating electron to **6.1.12**,which is a SemVer major change.
npm WARN audit Updating spectron to **10.0.1**,which is a SemVer major change.
npm WARN audit Updating electron-builder to **5.5.0**,which is a SemVer major change.
