### ISSUE TITLE
electron + webpack + angular

### ISSUE THREAD

**Issue by thamizh-qwerty** [reZach/secure-electron-template#137]
Like to use angular, instead of react. Tried by changing the files in release/app/renderer. 

Is it possible to use 'electron + webpack + angular' with configuration you mentioned in secure-electron-template?

**Comment by corybsa** [comment]
I created a template repo based on this one to use Angular. You can check it out here [https://github.com/corybsa/secure-electron-angular-template](https://github.com/corybsa/secure-electron-angular-template)
