### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by athenawisdoms** [reZach/secure-electron-template#19]
When I run the following commands

```
git clone https://github.com/reZach/secure-electron-template .
npm install
npm run dev
```

the electron app appears but shows a blank white screen and many errors in the console:

```
security-warnings.ts:179 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.
(anonymous) @ security-warnings.ts:179
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/index.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/encode.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/Encoder.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/utils/utf8.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/ExtensionCodec.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/ExtData.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/timestamp.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/utils/int.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/utils/typedArrays.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/decode.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/Decoder.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/utils/prettyByte.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/CachedKeyDecoder.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/decodeAsync.js.map
DevTools failed to parse SourceMap: chrome-error://chromewebdata/Users/athenawisdoms/test/node_modules/@msgpack/msgpack/dist/utils/stream.js.map
```

What might be the problem here? Thanks!

**System:**
- Mac OS X 10.15.3
- node v13.7.0
- npm 6.14.4

**Comment by reZach** [comment]
Thanks for reporting this @athenawisdoms. I've seen the error too, I believe it happens when the app loads before webpack is finished bundling. You can simply hit command + R to refresh the main screen and the errors should go away. I am open to a PR to fix this issue.

**Comment by reZach** [comment]
Note, this is _not_ an issue in production, since the webpack-dev-server is not used in production.

**Comment by reZach** [comment]
@athenawisdoms this is due to Chrome forcing source maps to be enabled by default. A [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=781648) was reported but marked as WontFix, so there is nothing we can do.

There's [a workaround](https://bugs.chromium.org/p/chromium/issues/detail?id=781648#c4) but only locally. There's also [this solution](https://stackoverflow.com/a/35004929/1837080), but it has to be done on every session. Sadly, we have to live with this.

**Comment by ShlomiRex** [comment]
> @athenawisdoms this is due to Chrome forcing source maps to be enabled by default. A [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=781648) was reported but marked as WontFix, so there is nothing we can do.
> 
> There's [a workaround](https://bugs.chromium.org/p/chromium/issues/detail?id=781648#c4) but only locally. There's also [this solution](https://stackoverflow.com/a/35004929/1837080), but it has to be done on every session. Sadly, we have to live with this.

It's 2021 and I have simillar problem. Still not fixed?

**Comment by reZach** [comment]
> > @athenawisdoms this is due to Chrome forcing source maps to be enabled by default. A [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=781648) was reported but marked as WontFix, so there is nothing we can do.
> > There's [a workaround](https://bugs.chromium.org/p/chromium/issues/detail?id=781648#c4) but only locally. There's also [this solution](https://stackoverflow.com/a/35004929/1837080), but it has to be done on every session. Sadly, we have to live with this.
> 
> It's 2021 and I have simillar problem. Still not fixed?

I am welcome if you are able to do additional digging into this to provide a solution here 🙂. The last I remember doing research, the issue is in Chromium and not something we can do to fix this within Electron.
