### ISSUE TITLE
Electron should host app from a non-file:/// origin

### ISSUE THREAD

**Issue by moloch--** [reZach/secure-electron-template#2]
Running from a `file:///` origin is insecure, [for example](https://github.com/moloch--/reasonably-secure-electron#signal-desktop). A simple [solution](https://github.com/moloch--/reasonably-secure-electron#origin-security)

**Comment by reZach** [comment]
Great, thanks for sharing this @moloch--! I'll see to it to put this code in the template.

**Comment by reZach** [comment]
It seems this method of loading pages doesn't play well with the webpack dev server, I'll have to futz around with it more.

**Comment by moloch--** [comment]
[`protocol.interceptFileProtocol`](https://electronjs.org/docs/api/protocol#protocolinterceptfileprotocolscheme-handler-completion) can be used to limit certain uses of `file://` but is less secure than doing away with it entirely.
