### ISSUE TITLE
Issue with default app on Windows

### ISSUE THREAD

**Issue by avrahams1** [reZach/secure-electron-template#21]
Hi,

First, I'd like to thank you for the enormous amounts of work it must have taken to make this basic boiler plate project, I truly appreciate it!

I cloned the project on a Windows machine (10, latest) and ran the `npm run dist-windows` command. (after an `npm install` of course)
I did absolutely no further changes.

When I try running the resulting installer, I get this error:

![image](https://user-images.githubusercontent.com/26322761/82129362-c60ab580-97ca-11ea-9174-00accee6af7b.png)

I'd appreciate any help in the matter, I assume I did something wrong, and I'd like to know why, I've literally started looking into this whole Electron thing today.

Windows version: 10.0.0.18362 Build 18362
NPM version: 6.14.4
Node version: 12.16.3

Thanks.

**Comment by reZach** [comment]
Thanks for reporting this @avrahams1. I was able to replicate this and push out a new release, can you please get the latest from master and see if your issue is fixed.

**Comment by avrahams1** [comment]
I actually tried that solution, but I installed lodash as a dev dependency, which probably made it not be included in the final exe :(
This did the trick, thanks!
