### ISSUE TITLE
Terminal throws errors with Exit status 1 when exiting `npm run dev`

### ISSUE THREAD

**Issue by heart-of-code** [reZach/secure-electron-template#23]
### Reproduce
```dos
npm install
npm run dev
[wait for application to load]
[click "X" to close window]
```

### Terminal Output
```dos
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! markdown-to-module@0.0.1 dev: `concurrently "npm run dev-server" "cross-env NODE_ENV=development electron ." -k`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the markdown-to-module@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Is there a way to get the dev scripts to exit cleanly?

**Comment by reZach** [comment]
Hi @heart-of-code thanks for reporting this issue. 
I've pushed [an update](https://github.com/reZach/secure-electron-template/releases/tag/v4.0.7), can you get the latest from master and see if your issue is fixed?

**Comment by heart-of-code** [comment]
@reZach exits cleanly now! Thank you so much! It's a relief not to see a bunch of big red warning messages every time I close the app 😄
