### ISSUE TITLE
We pack development server preload.js

### ISSUE THREAD

**Issue by rsouthworth** [reZach/secure-electron-template#25]
I cannot access the renderer UI hosted by the Web pack dev server within a Chrome browser because the main Electron process is adding the preload script. Is there a way to continue debugging renderer UI processes in Chrome via the We pack dev server please?

**Comment by reZach** [comment]
@rsouthworth I'm not quite sure what you mean. Are you saying that you cannot debug pages the renderer script renders? Adding a `debugger;` statement should automatically debug any page the renderer process is rendering.

Please help clarify your question, I want to help understand your concerns about the template.

**Comment by rsouthworth** [comment]
Thank you for your reply. I am trying to use Chrome to debug a renderer process. The preload.js is part of the Electron app being launched. I was hoping I could access the API into the Electron main process exposed by the preload script. I don't think it is possible and I have to work with dev tools in Electron and not in Chrome. It was convenient accessing the Webpack Dev server directly in Chrome whilst using React and Electron.

**Comment by reZach** [comment]
@rsouthworth are you speaking of debugging the preload.js? Yes, if so, I do not how to debug that file. If you do learn how to debug this file, please share with me!

**Comment by rsouthworth** [comment]
Sort of. I am trying to debug http://localhost:40992/ in Chrome but can't because of the preload scrips and lack of communication with the Electron main process because the context bridge API isn't on the window object. I don't know if it is possible. Maybe close this issue as debugging Electron itself works OK. Thank you very much for your replies.

**Comment by reZach** [comment]
@rsouthworth do you mean this?
![image](https://user-images.githubusercontent.com/4740370/84097249-96199100-a9c9-11ea-978d-d8e830ad3059.png)

**Comment by rsouthworth** [comment]
I am using React via create-react-app and I could debug that with a Webpack dev server and Chrome in localhost:40922

In Electron, when using the preload.js script to expose the Api in a renderer process from the main process you can't debug in the renderer process any longer in Chrome because the window object has not been manipulated by the Electron main process to add in the Api objects.

It isn't a problem because you can use the full Electron application and debug that with the Chrome developer tools. It was just very quick and easy to debug at localhost:40922 in Chrome. I don't know it can be solved easily.

Thank you very much for getting back to me.

![image](https://user-images.githubusercontent.com/12004759/84183611-143a6e00-aa84-11ea-89ce-a9e10b1b812f.png)

**Comment by reZach** [comment]
Understood, you'll probably want to open an issue up in [the electron](https://github.com/electron/electron) repository.

I noticed you use the i18nextElectronBackend, this backend works in this repository, on a fresh install - are you trying to do something custom and having trouble debugging?

**Comment by rsouthworth** [comment]
Thanks for your reply. I think I have solved debugging now with React reloading on source code edit and Electron restarting on source code edit. The screenshot was from your repo running in dev and the error visible in the browser because the preload scripts are Electron specific.
