### ISSUE TITLE
node js fs module is not working

### ISSUE THREAD

**Issue by antim-stream** [reZach/secure-electron-template#28]
Uncaught Error: Cannot find module 'fs'
    at webpackMissingModule (bundle.js:1115)
    at Module../app/src/core/root.jsx (bundle.js:1115)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Module../app/src/index.jsx (index.jsx:1)
    at __webpack_require__ (bootstrap:789)
    at fn (bootstrap:100)
    at Object.1 (log.js:59)
    at __webpack_require__ (bootstrap:789)
    at bootstrap:856

**Comment by reZach** [comment]
@antim-stream please provide more information here. The template works as-is, you must be doing something custom?

**Comment by antim-stream** [comment]
yes i need electron-builder, react and node js modules so after adding nodeIntegration true also i am not able to use any of the node js module
 webPreferences: {
      nodeIntegration: true,
 },

help needed

**Comment by antim-stream** [comment]
> yes i need electron-builder, react and node js modules so after adding nodeIntegration true also i am not able to use any of the node js module
> webPreferences: {
> nodeIntegration: true,
> },
> 
> help needed

**Comment by antim-stream** [comment]
yes i need electron-builder, react and node js modules so after adding nodeIntegration true also i am not able to use any of the node js module
webPreferences: {
nodeIntegration: true,
},

help needed

**Comment by antim-stream** [comment]
> @antim-stream please provide more information here. The template works as-is, you must be doing something custom?

yes i want to use node js module and for that i have done this
webPreferences: {
 nodeIntegration: true,
},

**Comment by reZach** [comment]
@antim-stream You can't simply use `fs` the normal way. You can only use `fs` in main.js. You must pass messages between the renderer and main process in order to use `fs`. Does this make sense or do you need additional information?

**Comment by reZach** [comment]
@antim-stream Have you figured this out? I can spend a little bit of time writing up a sample if you need one.

**Comment by antim-stream** [comment]
yes i tried out but no luck.
i need not only fs module outside the render but also needed other node js modules

**Comment by reZach** [comment]
@antim-stream Please check out [this page](https://github.com/reZach/secure-electron-template/blob/master/docs/newtoelectron.md).

**Comment by reZach** [comment]
@antim-stream did my explanation help you?

**Comment by reZach** [comment]
Going to close this @antim-stream , let me know if I need to re-open.

**Comment by eramudeep** [comment]
i have tried to  use ### `https://electron.guide/electron-alert/`

after integrating the minimal example 
its throwing error **fs module not found**

its been 3 days I am stuck

**Comment by reZach** [comment]
@eramudeep it's likely that package isn't written to support using IPC. I'd suggest you try and follow the [instruction steps](https://sweetalert2.github.io/#download) for SWAL directly in your app.
