### ISSUE TITLE
Lack of ContextIsolation & Insecure Preload

### ISSUE THREAD

**Issue by moloch--** [reZach/secure-electron-template#3]
You should also avoid exposing any IPC objects directly to the DOM from the preload script, though without `ContextIsolation` it's trivial to escape the sandbox using prototype pollution attacks.

There's a couple different ways to approach this, my solution is [detailed here](https://github.com/moloch--/reasonably-secure-electron#playing-in-the-sandbox) but certainly isn't the only way to address the problem.

**Comment by reZach** [comment]
This is a high-priority to me as well. I've been talking in [this thread](https://github.com/electron/electron/issues/21437#issuecomment-573522360) and got pointed to the right direction (in a similar vein to your example) from one of the contributors of Electron.

I plan to implement IPC securely as I hook up i18n and an electron store in the coming days.

**Comment by reZach** [comment]
@moloch-- I've turned `contextIsolation` back on, as well as updated the preload to use the new api methods instead of `window.[x]....`. [commit](https://github.com/reZach/secure-electron-template/commit/47504312020e89a47e56ad248efb4d3d7b8664c4)

Do you have any further suggestions looking at my commit?

**Comment by MarshallOfSound** [comment]
@reZach That commit just blanket exposes all of `ipcRenderer`, as I outlined in my comment you linked above the safe thing to do here is expose the _minimal_ required API surface.  In it's current state anything in the main context can send / listen for **any** ipc message.

**Comment by moloch--** [comment]
@MarshallOfSound (unsurprisingly) is spot on, you need to whitelist specific IPC interactions between the renderer process and the main process to have any hope of enforcing isolation. My solution here is linked above using `postMessage()` (to avoid even directly exposing a preload script symbol) and a preload script that controls what messages can be sent/received.

**Comment by reZach** [comment]
Thanks @moloch-- and @MarshallOfSound. If you are interested, I've updated my [i18next-electron-fs-backend](https://github.com/reZach/i18next-electron-fs-backend) repo with the [following commit](https://github.com/reZach/i18next-electron-fs-backend/blob/master/src/index.js#L13-L73) that I think adequately limits the channels the ipcRenderer/ipcMain can communicate on. 

This change accomplishes a few things I was looking for:
1. Keeping the channel keys in the package itself.
2. Only allows the channel keys defined in the package for communication between the main and renderer processes.
3. Allows the user to write nice bindings in the preload.js and main.js scripts to hook everything up.

I was considering a nonce or secret key or some other form of anti-tampering but I couldn't/didn't want to do that tonight so we (I) can table it unless the community feels its pressing to add. If you have more concerns I can re-open this issue.

Thanks both for your feedback!
