### ISSUE TITLE
Auto-updating feature

### ISSUE THREAD

**Issue by dpieski** [reZach/secure-electron-template#37]
From your readme: 
> There are a number of additions that I'd like to implement in this repository, namely auto-updating

I actually just got this setup on a sample/template app of mine using GitLab. It's my understanding that it is actually easier to get setup using GitHub as GitHub is a specific provider vs using the generic provide for GitLab.
 
Essentially, when I commit to the `master` branch, it builds the app, adds the `*.exe` artifact as a package on GitLab, and links that package as an asset on the release. When my app launches, it waits 10sec to check for an update, then checks every 2min (obvs too often but needed for testing purposes). When an update is detected, it pops up a window to let the user know. Downloads the update and asks the user if they want to restart now to install the update or install on exit. It then installs as appropriate.

What are you looking for in your template to implement auto-updating? What would you like to see the process be? I don't mind making a PR if I know more about what you are looking for.

If you would like, I can link my repo from GitLab.

I know that there is one major security concern with it right now that I have not taken the time to fix. But it otherwise functions as expected.

**Comment by reZach** [comment]
Thanks for starting this conversation @dpieski . I've thought about it a little bit and it looks like auto-updating is pretty dependent on your own environment/services/storage capacity, so I'm against making something fit in this template that is for one purpose. 

The idea I like more is a package or something we can install into this template which allows anyone to deploy auto-updating as they like.

I'm a little concerned about your "security concern" you list, we wouldn't want that to be in place for a secure template.

**Comment by dpieski** [comment]
My security concern is essentially specific to when I am using a **private** GitLab project on the **free** GitLab tier.
* Free GitLab does not allow Project Tokens, so I would have to use a [personal access token](https://docs.gitlab.com/ee/user/profile/personal_access_tokens.html#creating-a-personal-access-token). 

My electron app would need to access the artifacts of the CI job that compiles the app, so, since it is a private project, I have to use a `read_api` Personal Access Token to get there. But that read permission is to the whole account, not just the project. 

I do not yet know how to get GitLab CI to compile the app with the Personal Access Token if the Personal Access Token is not committed. Then there is also the issue of decompiling the electron app to retrieve the Personal Access Token.

Of course, this is not an issue if you are using a **public** project since the artifacts from the CI build are openly accessible at that point so you would not need any authentication.

**Comment by reZach** [comment]
Sorry for not replying in a timely manner @dpieski. I've thought of this a bit and I feel your particular use case can't be extrapolated in a generic way. I feel I would be open to an auto-updating feature that is provider-agnostic, do you feel your work can get you there or is it solely with GitLab?

**Comment by dragonDScript** [comment]
@reZach I upvote this feature.
We could create a separate module for this that takes some environment variables and does everything for you. I don't see any security concerns for that.

**Comment by reZach** [comment]
@dragonDScript is this something you can research and began to create as a separate NPM package that this template could use?

**Comment by dragonDScript** [comment]
> @dragonDScript is this something you can research and began to create as a separate NPM package that this template could use?

Well, I don't have a lot of time right now? Could you create it?

**Comment by reZach** [comment]
> 
> 
> > @dragonDScript is this something you can research and began to create as a separate NPM package that this template could use?
> 
> Well, I don't have a lot of time right now? Could you create it?

I do not either, that is why I asked you 😄.

**Comment by reZach** [comment]
@dragonDScript @dpieski I was able to find [a repo](https://github.com/iffy/electron-updater-example) that should give you all the information you need to set up auto-updating. Since updating really depends on the project, I feel this example can help you both (but I [did now](https://github.com/reZach/secure-electron-template/commit/4b2f54980f156f6de73291fa654122ddab164fcd#diff-8a945ee3b98eae797d4005d9f8f883c3b9c074f9ce778464bbc44c689b78b060R32-R35) provide guidance in the source code for others in case they have the same question).
