### ISSUE TITLE
App is a blank, white screen when starting up

### ISSUE THREAD

**Issue by anubra266** [reZach/secure-electron-template#38]
It only comes up after I reload.

**Comment by reZach** [comment]
This problem has been known for a while. I've only heard this is an issue in development mode, so I'm open to some help in figuring it out.

**Comment by reZach** [comment]
@anubra266 I _think_ the issue should be fixed [now](https://github.com/reZach/secure-electron-template/releases/tag/v7.0.0). Please re-open if you continue to have issues with this.
