### ISSUE TITLE
App open in blank while run prod

### ISSUE THREAD

**Issue by abfurlan** [reZach/secure-electron-template#40]
When run the program in prod mode nothing is rendered and the screen is blank

**Comment by abfurlan** [comment]
I did update to v11.0.1 from electron and it worked

https://www.electronjs.org/releases/stable#release-notes-for-v1101

**Comment by reZach** [comment]
Thanks for the discovery @abfurlan , an [update](https://github.com/reZach/secure-electron-template/releases/tag/v7.0.0) has been pushed to the repo.

**Comment by eramudeep** [comment]
i am still facing the same problem.
Version: 
`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) legitquest/1.0.2 Chrome/91.0.4472.77 Electron/13.1.2 Safari/537.36"`

**Comment by reZach** [comment]
@eramudeep can you change `devTools` to **true** and see if any error is in the console when running `npm run prod`?

```js
  // Create the browser window.
  win = new BrowserWindow({
    width: 800,
    height: 600,
    title: "Application is currently initializing...",
    webPreferences: {
      devTools: true, //isDev
    }
  });
```

**Comment by abfurlan** [comment]
@eramudeep I discovered a problem with Symantec Antivirus. It for some reason blocks rendering in prod mode.
What's antivirus do you use? Try disabling it to try discovery if be the same problem.

**Comment by eramudeep** [comment]
> @eramudeep I discovered a problem with Symantec Antivirus. It for some reason blocks rendering in prod mode.
> What's antivirus do you use? Try disabling it to try discovery if be the same problem.

Thanks for the answer.

actually, the problem was with React router.
I changed it to 
` <HashRouter>  
        <Switch>
          <Route exact path={"/"} component={Login}></Route>
          <Route exact path={"/welcome"} component={Welcome}></Route> 
          <Route  path={"*"}  exact insecure component={NotFound} ></Route>  
        </Switch>
      </HashRouter>
`
Did fix my problem.
Now it's working like a charm on Mac, Winx86 and Ubuntu :)

**Comment by eramudeep** [comment]
> @eramudeep can you change `devTools` to **true** and see if any error is in the console when running `npm run prod`?
> 
> ```js
>   // Create the browser window.
>   win = new BrowserWindow({
>     width: 800,
>     height: 600,
>     title: "Application is currently initializing...",
>     webPreferences: {
>       devTools: true, //isDev
>     }
>   });
> ```

this helped to fix the errors.

> the cause was mysql-importer

**Comment by eramudeep** [comment]
bad luck.
it's working on Mac, Winx86 and Ubuntu :)
**but not working on ubuntu 16**  :(

**Comment by reZach** [comment]
😢
