### ISSUE TITLE
Question: Template without react

### ISSUE THREAD

**Issue by ehhc** [reZach/secure-electron-template#41]
hi there,
I’m new to electron and want to build a small, quick and simple electron app relying only on JavaScript.
Is there any way to get your cool template without all the react overhead i don't need?
Do you know about any forks or similar, you can recommend?

Thanks in advance :)

**Comment by ehhc** [comment]
I figured it out myself. Thanks for your project :)

**Comment by reZach** [comment]
I am glad you figured it out @ehhc. If you can consider writing a little bit about your steps on this [page](https://github.com/reZach/secure-electron-template/blob/master/docs/faq.md) to possibly help others in the future with the same question, as I am sure you are not the only one with this question.

**Comment by reZach** [comment]
@ehhc there [are steps](https://github.com/reZach/secure-electron-template/issues/57#issuecomment-777891491) which you may follow to make this a JS-only template. They are _proposed_ changes and may not reflect all the work that is necessary for this template.

**Comment by ehhc** [comment]
Hi @reZach

i'm sorry that i didn't responded. Unfortunately, i had a lot of work to do in my job taking my time..

Cool that you documented a way to remove the react-related stuff.

And thanks for pinging me and linking it here.

Thanks again for your great work :)
