### ISSUE TITLE
Cannot remove EventListener from IpcRenderer channel

### ISSUE THREAD

**Issue by nalexander50** [reZach/secure-electron-template#43]
Love this template! Not only did it make me feel more comfortable writing a secure Electron app, but it also helped solidify some fundamental Electron concepts.

I have run into a problem that I can't seem to nail down. Using this template, I cannot remove an event listener from an `IpcRenderer` channel by using `.off` or `.removeListener`. As long as the listener functions are in scope, they continue to listen and receive messages.

With all the debugging I have done, I am either missing something fundamental or I am running into a cloning/copying issue and my function name is getting lost. Disclaimer, I am running an Angular application under Electron which may contribute to weirdness.

**Angular Service**

``` typescript
import { Injectable } from '@angular/core';

import { Observable, Subject, of, merge } from 'rxjs';
import { filter, map } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class InputFileService {

  private _channelName = 'input-file';

  constructor() { }

  getInputFileData(): Observable<string> {
    if (window.electron) {
      const responseSubjet = new Subject<string>();

      function onReceive(...args: any[]): void {
        responseSubjet.next(args[0]);
        responseSubjet.complete();
        window.electron.stopReceiving('input-file', onReceive);
      }

      window.electron.receive(this._channelName, onReceive);

      return merge(
        responseSubjet.asObservable(),
        of(window.electron.send(this._channelName))
      ).pipe(
        filter(value => !!value), // double negative to force check truthiness
        map(value => value as string)
      );
    }

    return of();
  }
}

```

**preload.js**
``` javascript
const {
    contextBridge,
    ipcRenderer
} = require('electron');

const ALLOWED_CHANNELS = [
    'input-file',
    'context-menu'
];

contextBridge.exposeInMainWorld('electron', {
    send: (channel, ...args) => {
        // whitelisted channels only
        if (ALLOWED_CHANNELS.includes(channel)) {
            ipcRenderer.send(channel, ...args);
        }
    },

    receive: (channel, callback) => {
        // whitelisted channels only
        if (ALLOWED_CHANNELS.includes(channel)) {
            ipcRenderer.on(channel, (_, ...args) => {
                // deliberately protect `event` as it includes `sender`
                callback(...args);
            });
        }
    },

    stopReceiving: (channel, listener) => {
        // whitelisted channels only
        if (ALLOWED_CHANNELS.includes(channel)) {
            ipcRenderer.off(channel, listener);
        }
    },

    once: (channel, callback) => {
        // whitelisted channels only
        if (ALLOWED_CHANNELS.includes(channel)) {
            ipcRenderer.once(channel, (_, ...args) => {
                // deliberately protect `event` as it includes `sender`
                callback(...args);
            });
        }
    },

    sendSync: (channel, ...args) => {
        // whitelisted channels only
        if (ALLOWED_CHANNELS.includes(channel)) {
            return ipcRenderer.sendSync(channel, ...args);
        }
    },
});
```

**Window extension**
``` typescript
declare global {
  interface Window {
    electron: {
      send: (channel: string, ...args: any[]) => void,
      receive: (channel: string, callback: (...args: any[]) => void) => void,
      stopReceiving: (channel: string, listener: (...args: any[]) => void) => void,
      once: (channel: string, listener: (...args: any[]) => void) => void,
      sendSync: (channel: string, ...args: any[]) => any;
    };
  }
}
```

While running under the Visual Studio Code debugger, if I set a breakpoint on the `.off` line in `preload.js`, the `name` property of the `listener` function is empty string. It seems like my named function `onReceive` is getting passed as an anonymous function somewhere. If I just use `once` instead, the listener is removed as expected.

**Comment by reZach** [comment]
Thanks @nalexander50. `stopReceiving` is calling `.off`, but based on the docs, I feel you should be using [`.removeListener`](https://www.electronjs.org/docs/api/ipc-renderer#ipcrendererremovelistenerchannel-listener) instead (`.off` doesn't look like it's a function of ipcRenderer)? If that does not work for you, you said you tried `.removeAllListeners` and it didn't work?

**Comment by nalexander50** [comment]
@reZach The `.off` is a typo. In my running code, I have `.removeListener` instead. I was calling both (I've seen StackOverflow answers mention `.off` so I tried it for good measure) and when posting this issue I accidentally deleted the wrong line. All that to say: `.removeListener` also exhibits the same non-working behavior -- the listener is not actually removed.

If I call `.removeAllListeners`, that does work. Which leads me further to believe that I have some kind of function identity problem.

**Comment by reZach** [comment]
Ah @nalexander50, understood. I'll ask you to try to create a MVP without angular and see if you can replicate the issue. That should help nail it down if it's an angular or electron issue.

**Comment by nalexander50** [comment]
In classic fashion, after many hours of debugging, I discovered the problem and it was so, so obvious. I am suspending my programmer's license for the weekend.

In `preload` when I call `ipcRenderer.on` (inside of `receive`), I am passing in an anonymous function that calls `callback`! But, I was trying to remove `callback` as a listener -- it was never a listener! If I actually `removeListener` the anonymous function passed into `.on`, wouldn't you know it, the listener is removed.

Side note, I actually followed a different repo with a very similar name, so I was actually barking up the wrong tree coming here. My apologies! Either way, maybe some hopeless soul such as myself will find this in the future and realize they are making same mistake.

**Comment by Vishal1419** [comment]
@nalexander50 I am also facing the same issue. Can you please check my code and suggest what am I doing wrong?

```
const { contextBridge, ipcRenderer } = require('electron')
const { CONTENT_EVENTS } = require('../../ipc-events');

contextBridge.exposeInMainWorld(
  'electron', {
    send: (channel, data) => {
      if (Object.values(CONTENT_EVENTS.C2E).includes(channel)) {
        ipcRenderer.send(channel, data)
      }
    },
    receive: (channel, func) => {
      if (Object.values(CONTENT_EVENTS.E2C).includes(channel)) {
        // Deliberately strip event as it includes `sender` 
        ipcRenderer.on(channel, (event, ...args) => func(...args))
      }
    },
    receiveOnce: (channel, func) => {
      if (Object.values(CONTENT_EVENTS.E2C).includes(channel)) {
        // Deliberately strip event as it includes `sender` 
        ipcRenderer.once(channel, (event, ...args) => func(...args))
      }
    },
    removeListener: (channel, func) => {
      if (Object.values(CONTENT_EVENTS.E2C).includes(channel)) {
        ipcRenderer.removeListener(channel, (event, ...args) => func(...args))
      }
    }
  }
)
```

**Comment by Vishal1419** [comment]
For someone in the future (here is my solution):
```
const { contextBridge, ipcRenderer } = require('electron')
const { CONTENT_EVENTS } = require('../../ipc-events');

contextBridge.exposeInMainWorld(
  'electron', {
    send: (channel, data) => {
      if (Object.values(CONTENT_EVENTS.C2E).includes(channel)) {
        ipcRenderer.send(channel, data)
      }
    },
    receive: (channel, func) => {
      if (Object.values(CONTENT_EVENTS.E2C).includes(channel)) {
        // Deliberately strip event as it includes `sender` 
        const subscription = (event, ...args) => func(...args);
        ipcRenderer.on(channel, subscription);
        return () => {
          ipcRenderer.removeListener(channel, subscription);
        }
      }
    },
    receiveOnce: (channel, func) => {
      if (Object.values(CONTENT_EVENTS.E2C).includes(channel)) {
        // Deliberately strip event as it includes `sender` 
        ipcRenderer.once(channel, (event, ...args) => func(...args))
      }
    },
    removeAllListeners: (channel, func) => {
      if (Object.values(CONTENT_EVENTS.E2C).includes(channel)) {
        ipcRenderer.removeAllListeners(channel)
      }
    }
  }
)

```

**Comment by domis4** [comment]
@Vishal1419 
this is the correct way 👍

**Comment by jcarpenter** [comment]
> For someone in the future (here is my solution):
> 
> ```
> const { contextBridge, ipcRenderer } = require('electron')
> const { CONTENT_EVENTS } = require('../../ipc-events');
> 
> contextBridge.exposeInMainWorld(
>   'electron', {
>     send: (channel, data) => {
>       if (Object.values(CONTENT_EVENTS.C2E).includes(channel)) {
>         ipcRenderer.send(channel, data)
>       }
>     },
>     receive: (channel, func) => {
>       if (Object.values(CONTENT_EVENTS.E2C).includes(channel)) {
>         // Deliberately strip event as it includes `sender` 
>         const subscription = (event, ...args) => func(...args);
>         ipcRenderer.on(channel, subscription);
>         return () => {
>           ipcRenderer.removeListener(channel, subscription);
>         }
>       }
>     },
>     receiveOnce: (channel, func) => {
>       if (Object.values(CONTENT_EVENTS.E2C).includes(channel)) {
>         // Deliberately strip event as it includes `sender` 
>         ipcRenderer.once(channel, (event, ...args) => func(...args))
>       }
>     },
>     removeAllListeners: (channel, func) => {
>       if (Object.values(CONTENT_EVENTS.E2C).includes(channel)) {
>         ipcRenderer.removeAllListeners(channel)
>       }
>     }
>   }
> )
> ```

Thanks for sharing @Vishal1419. Can you clarify how you actually remove the event listener? I'm unclear on how to work with or access the returned `ipcRenderer.removeListener(channel, subscription)` inside the `receive` method. In my case, I want to call removeListeners from inside Svelte components when they're destroyed.

**Comment by Vishal1419** [comment]
@jcarpenter I am glad you found the answer! This is the exact thing that I am doing, but in React.

**Comment by redalert253225** [comment]
@Vishal1419
thank for your idea to save me from hours of thinking

**Comment by BangHyeongSik** [comment]
@Vishal1419
This is the best code I've found. 😄

**Comment by walrus811** [comment]
@Vishal1419 
You are my life saver 😄.

**Comment by v-dawg** [comment]
```javascript
window.api.listen("event", update)
window.api.removeListener("event", update)
```
If this does not work it should probably be documented.

**Comment by 0x457** [comment]
> @Vishal1419 You are my life saver 😄.

me too

**Comment by Nikolay03** [comment]
@Vishal1419 It works—after many hours, I finally found a working method.
