### ISSUE TITLE
[Question][Improvement] Enable usage of async/await.

### ISSUE THREAD

**Issue by chickoocoutinho** [reZach/secure-electron-template#45]
What are your thought on changing the bable preset to enable use of async/await with the template.

**Comment by reZach** [comment]
I'm not leaning any particular way of either to do/refrain from such a change. Can you list out the pros/cons as you see them if this feature would be to enabled @chickoocoutinho?

**Comment by chickoocoutinho** [comment]
[correct me if I am wrong]
Right now the bable-preset-env is set to default, resulting in transforming of all code to ES5.
But since the template uses the latest version of electron, it will also use the latest verision of chromium which supports ES6 and so on.
So it is better if the bable-preset-env is set to the latest version of chromium.

https://dev.to/jnielson94/demystifying-babel-preset-env-3h88

I found this medium article explaining the pros and cons of async/await.
https://medium.com/@benlesh/async-await-it-s-good-and-bad-15cf121ade40

**Comment by reZach** [comment]
@chickoocoutinho Can you see if this [latest release](https://github.com/reZach/secure-electron-template/releases/tag/v7.1.0) supports your async/await code?

**Comment by chickoocoutinho** [comment]
Yes it does
