### ISSUE TITLE
"Extension server error: Operation failed: Permission denied"

### ISSUE THREAD

**Issue by NiloDrumond** [reZach/secure-electron-template#48]
Im getting this error over and over: 
``` "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/extensions/extensions.js```
Also, React Dev Tools is not working, I tried a lot of different ways:
- https://www.electronjs.org/docs/tutorial/devtools-extension
- https://stackoverflow.com/questions/61894248/electron-js-devtoolsinstaller-browserwindow-adddevtoolsextension-is-depreca
- https://github.com/dimitarnestorov/react-devtools-electron#readme

and of course `electron-devtools-installer` because it already came with the template, and was still throwing this error.

It doesn't break the application, but I still haven't managed to use React Dev Tools with this template. I also barely touched the template. (only removed redux related stuff because I won't use it)

Thanks!

Edit: 
Also, another problem that I'm having is: running yarn dev opens electron, but it only loads the app when I manually reload.

**Comment by reZach** [comment]
@NiloDrumond This should be fixed with [v7.0.2](https://github.com/reZach/secure-electron-template/releases/tag/v7.0.2). Thanks for reporting this. Solution was found [here](https://github.com/electron/electron/issues/12438#issuecomment-390211011).
