### ISSUE TITLE
Cloning repo and running results in "Uncaught Error: Cannot find module 'process/browser'"

### ISSUE THREAD

**Issue by Slapbox** [reZach/secure-electron-template#51]
OS: Windows 7 and Linux if you use `yarn`

Full error text:

```
bundle.js:2644 Uncaught Error: Cannot find module 'process/browser'
    at webpackMissingModule (bundle.js:2644)
    at Module../node_modules/@msgpack/msgpack/dist.es5+esm/utils/utf8.mjs (bundle.js:2644)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:61)
    at Module../node_modules/@msgpack/msgpack/dist.es5+esm/Encoder.mjs (bundle.js:1582)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:61)
    at Module../node_modules/@msgpack/msgpack/dist.es5+esm/encode.mjs (bundle.js:2231)
    at __webpack_require__ (bootstrap:21)
    at fn (hot module replacement:61)


webpackMissingModule | @ | bundle.js:2644
-- | -- | --
  | ./node_modules/@msgpack/msgpack/dist.es5+esm/utils/utf8.mjs | @ | bundle.js:2644
  | __webpack_require__ | @ | bootstrap:21
  | fn | @ | hot module replacement:61
  | ./node_modules/@msgpack/msgpack/dist.es5+esm/Encoder.mjs | @ | bundle.js:1582
  | __webpack_require__ | @ | bootstrap:21
  | fn | @ | hot module replacement:61
  | ./node_modules/@msgpack/msgpack/dist.es5+esm/encode.mjs | @ | bundle.js:2231
  | __webpack_require__ | @ | bootstrap:21
  | fn | @ | hot module replacement:61
  | ./node_modules/@msgpack/msgpack/dist.es5+esm/index.mjs | @ | bundle.js:2274
  | __webpack_require__ | @ | bootstrap:21
  | fn | @ | hot module replacement:61
  | ./node_modules/secure-electron-store/lib/index.js | @ | index.js:1
  | __webpack_require__ | @ | bootstrap:21
  | fn | @ | hot module replacement:61
  | ./app/src/pages/motd/motd.jsx | @ | bundle.js:7236
  | __webpack_require__ | @ | bootstrap:21
  | fn | @ | hot module replacement:61
  | ./app/src/core/routes.jsx | @ | bundle.js:7032
  | __webpack_require__ | @ | bootstrap:21
  | fn | @ | hot module replacement:61
  | ./app/src/core/root.jsx | @ | bundle.js:6990
  | __webpack_require__ | @ | bootstrap:21
  | fn | @ | hot module replacement:61
  | ./app/src/index.jsx | @ | bundle.js:7085
  | __webpack_require__ | @ | bootstrap:21
  | (anonymous) | @ | startup:4
  | (anonymous) | @ | startup:6


  ```

**Comment by Slapbox** [comment]
If I use `npm i` this doesn't occur, but then we get an endless stream of these messages in the terminal:

```
27316:0130/193504.888385:ERROR:CONSOLE(1)] "Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/extensions/extensions.js (1)
```

**Comment by Slapbox** [comment]
For `yarn` users:

```
npm i
yarn import
yarn
```

Finally, delete package.lock.json.

----

But @reZach if you know what causes the issue were the page has to be reloaded before it will work that's still a _minor_ issue.

**Comment by reZach** [comment]
@Slapbox I am open if you are willing to look into a solution to make `yarn` work natively for this template. I am sorry, I thought yarn should work without any hiccup!

To the issue with the "operation failed" message, that was fixed [here](https://github.com/reZach/secure-electron-template/issues/48).

**Comment by Slapbox** [comment]
Oddly that issue with needing to reload only occurs for me on Linux.

I think the issue is that the template relies on package `package-lock.json`. I think this could be remedied with more stringent dependency versions in `package.json`, but I'm not sure what package in particular causes the issue. Fortunately the workaround is pretty simple.

**Comment by reZach** [comment]
> 
> 
> Oddly that issue with needing to reload only occurs for me on Linux.
> 
> I think the issue is that the template relies on package `package-lock.json`. I think this could be remedied with more stringent dependency versions in `package.json`, but I'm not sure what package in particular causes the issue. Fortunately the workaround is pretty simple.

Yes I'd _love_ to know what package is causing this issue. I'm seeing **w3c-hr-time** uses `browser-process-hrtime` that's probably the culprit, but I don't know what's using it.

**Comment by Slapbox** [comment]
At least on Windows it doesn't seem that either of those packages are used by the repo.

```
{ secure-electron-template } webpackPreload » yarn why browser-process-hrtime
yarn why v1.22.4
[1/4] Why do we have the module "browser-process-hrtime"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 0.73s.
{ secure-electron-template } webpackPreload » yarn why w3c-hr-time
yarn why v1.22.4
[1/4] Why do we have the module "w3c-hr-time"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 0.66s.

```

Worth re-opening this issue? I haven't seen this issue since, but I've also been working on Windows since.

**Comment by reZach** [comment]
I'll reopen, I was looking at a different repo when I searched and found that!

`process/browser` is added in webpack.config due to [this comment](https://stackoverflow.com/a/64553486/1837080)

**Comment by reZach** [comment]
Closing this issue as I'm calling out the problem with yarn in this [pinned issue](https://github.com/reZach/secure-electron-template/issues/62).
