### ISSUE TITLE
"Audit" is already a name of a Yarn command - Consider renaming

### ISSUE THREAD

**Issue by Slapbox** [reZach/secure-electron-template#58]
The `audit` command for Electronegativity is a great addition! A minor issue though is that `yarn audit` is already built into Yarn, and because `yarn audit` is equal to `yarn run audit` that means this will interfere with Yarn. 

Running `yarn audit` ignores the command in the package.json in favor of the built-in command.

https://classic.yarnpkg.com/en/docs/cli/audit/

**Comment by reZach** [comment]
Thanks for reporting @Slapbox, fixed with [this release](https://github.com/reZach/secure-electron-template/releases/tag/v9.2.1).
