### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by adelinopds** [reZach/secure-electron-template#60]
Uncaught ReferenceError: global is not defined
    at jsonp chunk loading:42
    at bundle.js:106116
    at startup:6

**Comment by reZach** [comment]
@adelinopds what version of the template and what operating system are you using?

**Comment by adelinopds** [comment]
8.0.0

**Comment by adelinopds** [comment]
this problem I was able to solve, it was a problem in some dependencies that I installed
