### ISSUE TITLE
npm ERR! enoent This is related to npm not being able to find a file.

### ISSUE THREAD

**Issue by adelinopds** [reZach/secure-electron-template#61]
npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /home/adelino/Documentos/dev/electron/secure-electron-template/node_modules/@doyensec/electronegativity/dist/index.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/adelino/Documentos/dev/electron/secure-electron-template/node_modules/@doyensec/electronegativity/dist/index.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

problema de incompatibilidade com  o modulo @doyensec/electronegativity

**Comment by adelinopds** [comment]
sh: 1: concurrently: not found
npm ERR! code 127
npm ERR! path /home/adelino/Documentos/dev/electron/secure-electron-template
npm ERR! command failed
npm ERR! command sh -c concurrently --success first "node dev-scripts/prepareDevServer.js" "node dev-scripts/launchDevServer.js" -k

**Comment by reZach** [comment]
Can you run `npm i` to install dependencies you are missing @adelinopds? The error `concurrently not found` indicates it's not installed in your "node_modules" folder.

**Comment by adelinopds** [comment]
when i try to install, at the end of the installation some process deletes the node_modules.
A bizarre problem is happening

**Comment by reZach** [comment]
@adelinopds change `@doyensec/electronegativity` to `^1.8.0`, or remove this devDependency (in **package.json**) from the project. [Another user](https://github.com/reZach/secure-electron-template/issues/56#issue-806428115) has reported the same issue with that dependency.
