### ISSUE TITLE
yarn does not install dependencies correctly

### ISSUE THREAD

**Issue by reZach** [reZach/secure-electron-template#62]
`yarn` as a package manager does not currently work for the project. If you are using yarn, you'll have to follow these steps to install dependencies.

```
npm i
yarn import
yarn
```

Then, delete package.lock.json from the project.

--

You will get **bonus points** for helping resolve this bug (and all the gratitude of others who want to use `yarn` with this project 😄).

**Comment by whudson** [comment]
Seems to work fine for me with latest version of yarn on Windows 10.

**Comment by reZach** [comment]
Thanks @whudson! I will close this as the issue seems to be resolved (we can re-open if necessary).
