### ISSUE TITLE
Launching server crashing

### ISSUE THREAD

**Issue by foundbypass** [reZach/secure-electron-template#64]
running `npm run dev` gives me this output

<img width="826" alt="Skärmavbild 2021-02-17 kl  20 16 40" src="https://user-images.githubusercontent.com/66265306/108255845-0da8de00-715d-11eb-9950-08e47c85f32e.png">

**Comment by reZach** [comment]
@foundbypass what version of the template do you have and what OS are you on?

**Comment by reZach** [comment]
@foundbypass If you can apply [these changes](https://github.com/reZach/secure-electron-template/commit/21f523815e6bef33cb2faf16fcee30534f675f58) to your project, or pull the [latest release](https://github.com/reZach/secure-electron-template/releases/tag/v9.4.2), the template will now output to the console webpack compilation errors.

_^ If this is a webpack error_

**Comment by ma-anwar** [comment]
I am having the same issue, I just pulled the latest release today and am running on ubuntu 18.04.

**Comment by reZach** [comment]
FYI @foundbypass and @ma-anwar, thank you for your discussion. I've implemented the `process/browser.js` fix in [v9.5.0](https://github.com/reZach/secure-electron-template/releases/tag/v9.5.0).

**Comment by eramudeep** [comment]
i am having another problem 
<img width="1072" alt="Screenshot 2021-09-16 at 2 29 35 PM" src="https://user-images.githubusercontent.com/38516686/133583321-4db42c17-ac67-4abb-8fb0-f78eb9e663ca.png">
It stuck on this screen i waited for 1 Hour 
npm run prod is working fine 
**webpack.development.js**
`const HtmlWebpackPlugin = require("html-webpack-plugin");
const CspHtmlWebpackPlugin = require("csp-html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const { merge } = require("webpack-merge");
const base = require("./webpack.config");
const path = require("path");

module.exports = merge(base, {
  mode: "development",
  devtool: "source-map", // Show the source map so we can debug when developing locally
  devServer: {
    host: "localhost",
    port: "40992",
    hot: true, // Hot-reload this server if changes are detected
    compress: true, // Compress (gzip) files that are served
    contentBase: path.resolve(__dirname, "app/dist"), // Where we serve the local dev server's files from
    watchContentBase: true, // Watch the content base for changes
    watchOptions: {
      ignored: /node_modules/ // Ignore this path, probably not needed since we define contentBase above
    }
  },
  plugins: [
    new MiniCssExtractPlugin(),
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, "app/src/index.html"),
      filename: "index.html"
    }),
    new CspHtmlWebpackPlugin({
      "base-uri": ["'self'"],
      "object-src": ["'none'"],
      "script-src": ["'self'"],
      'style-src': ["'unsafe-inline'", "'self'", "'unsafe-eval'"], 
      "frame-src": ["'none'"],
      "worker-src": ["'none'"]
    })
  ]
})`

webpack.production.js
`const HtmlWebpackPlugin = require("html-webpack-plugin");
const CspHtmlWebpackPlugin = require("csp-html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const CssMinimizerPlugin = require("css-minimizer-webpack-plugin");
const { merge } = require("webpack-merge");
const base = require("./webpack.config");
const path = require("path");

module.exports = merge(base, {
  mode: "production",
  devtool: false,
  plugins: [
    new MiniCssExtractPlugin(),
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, "app/src/index.html"),
      filename: "index.html",
      base: "app://rse"
    }),
    // You can paste your CSP in this website https://csp-evaluator.withgoogle.com/
    // for it to give you suggestions on how strong your CSP is
    new CspHtmlWebpackPlugin(
      {
        "base-uri": ["'self'"],
        "object-src": ["'none'"],
        "script-src": ["'self'"],
        'style-src': ["'unsafe-inline'", "'self'", "'unsafe-eval'"],
        "frame-src": ["'none'"],
        "worker-src": ["'none'"]
      },
      {
        hashEnabled: {
          "style-src": false
        }
      }
    )
  ],
   
});`

**Comment by reZach** [comment]
@eramudeep Can you please check `/dev-scripts/webpack-dev-server[-error].log` for any related messages? I've [pushed a new release](https://github.com/reZach/secure-electron-template/releases/tag/v13.1.0) that stops the blocking behavior of spinning up the development server if it is not successful after 3 minutes.

**Comment by eramudeep** [comment]
> @eramudeep Can you please check `/dev-scripts/webpack-dev-server[-error].log` for any related messages? I've [pushed a new release](https://github.com/reZach/secure-electron-template/releases/tag/v13.1.0) that stops the blocking behavior of spinning up the development server if it is not successful after 3 minutes.

Thanks for the response. 
it's All my fault.
i included the appConfig.json file at the root of the project and using this in the Components with es6 Syntax.
It was working fine with the npm run prod
but app was not launching on npm run dev, i tried finding the errors in the log file I found nothing. after few hours of debugging and headbang, i started removing the component and it started working.

**Comment by reZach** [comment]
I'm glad you found the issue, @eramudeep!
