### ISSUE TITLE
Installation problems with npm

### ISSUE THREAD

**Issue by raphael10-collab** [reZach/secure-electron-template#65]
Just cloned and tried to install with npm. 

    (base) marco@pc01:~/webMatters/electronMatters$ git clone https://github.com/reZach/secure-electron-template.git
    Cloning into 'secure-electron-template'...
    remote: Enumerating objects: 405, done.
    remote: Counting objects: 100% (405/405), done.
    remote: Compressing objects: 100% (322/322), done.
    remote: Total 1552 (delta 120), reused 298 (delta 70), pack-reused 1147
    Receiving objects: 100% (1552/1552), 4.84 MiB | 6.79 MiB/s, done.
    Resolving deltas: 100% (641/641), done.

    (base) marco@pc01:~/webMatters/electronMatters$ cd secure-electron-template/

    (base) marco@pc01:~/webMatters/electronMatters/secure-electron-template$ npm i
    npm ERR! code ENOENT
    npm ERR! syscall chmod
    npm ERR! path /home/marco/webMatters/electronMatters/secure-electron-template/node_modules/@doyensec
    /electronegativity/dist/index.js

[2021-02-18T08_54_40_729Z-debug.log](https://github.com/reZach/secure-electron-template/files/6001504/2021-02-18T08_54_40_729Z-debug.log)

    npm ERR! errno -2
    npm ERR! enoent ENOENT: no such file or directory, chmod '/home/marco/webMatters/electronMatters/secure-electron-    
    template/node_modules/@doyensec/electronegativity/dist/index.js'
    npm ERR! enoent This is related to npm not being able to find a file.
    npm ERR! enoent 

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/marco/.npm/_logs/2021-02-18T08_54_40_729Z-debug.log

- node: v14.5.0
- O.S. : Ubuntu 18.04..4 Desktop

**Comment by reZach** [comment]
@raphael10-collab, please continue this conversation with the team that maintains that package [here](https://github.com/doyensec/electronegativity/issues/87). I do not to believe this error is with this template. I will re-open if the error is with this template and investigate, however.
