### ISSUE TITLE
Does 'Auxclick' exist as a Blink feature?

### ISSUE THREAD

**Issue by Slapbox** [reZach/secure-electron-template#68]
It appears here https://github.com/reZach/secure-electron-template/blob/f432f5d890f64a7741aa31d003187b4f00b81886/app/electron/main.js#L68

I wasn't able to find a comprehensive list of Blink features but on this page that I did find, I couldn't find `Auxclick`.

https://chromium.googlesource.com/chromium/src/+/master/third_party/blink/renderer/platform/runtime_enabled_features.json5

----

@reZach in any event, could you share the rationale for disabling Auxclick? If the idea is that it would prevent additional mouse buttons from acting as normal left clicks, it doesn't seem to work. I'm not sure that's the intended purpose though.

**Comment by reZach** [comment]
This comes from https://github.com/doyensec/electronegativity, see below.

![image](https://user-images.githubusercontent.com/4740370/109376422-f4eda600-7889-11eb-9291-79b47aff0564.png)

**Comment by Slapbox** [comment]
Thanks for the info!

In my testing that behavior doesn't seem to be the default anymore - I can't get middle click to do anything without explicitly programming it - but better safe than sorry.
