### ISSUE TITLE
Remove remote event callbacks once template is updated to Electron v14

### ISSUE THREAD

**Issue by netpoetica** [reZach/secure-electron-template#70]
All of the `app.on` calls in `main.js` [here](https://github.com/reZach/secure-electron-template/blob/master/app/electron/main.js#L272) are using deprecated calls - are these necessary anymore?

When I convert the main.js file to a .ts file instead, it allows us to pickup electron.d.ts where these calls are marked as deprecated:
```
    /**
     * Emitted when `remote.getGlobal()` is called in the renderer process of
     * `webContents`. Calling `event.preventDefault()` will prevent the global from
     * being returned. Custom value can be returned by setting `event.returnValue`.
     *
     * @deprecated
     */
    on(event: 'remote-get-global', listener: (event: Event,
                                              webContents: WebContents,
                                              globalName: string) => void): this;
    once(event: 'remote-get-global', listener: (event: Event,
                                              webContents: WebContents,
                                              globalName: string) => void): this;
    addListener(event: 'remote-get-global', listener: (event: Event,
                                              webContents: WebContents,
                                              globalName: string) => void): this;
    removeListener(event: 'remote-get-global', listener: (event: Event,
                                              webContents: WebContents,
                                              globalName: string) => void): this
```

Per [this Github issue](https://github.com/electron/electron/issues/21408), the remote module has been removed. Should this code also be removed from main? Is it safe to remove this code?

Thanks!

**Comment by reZach** [comment]
I'll keep this code in [until Electron 14](https://github.com/electron/electron/issues/21408#issue-533651777) where it doesn't make sense to keep it at that point (since it will be gone). Thanks for bringing this up!

**Comment by netpoetica** [comment]
Awesome - I wasn't clear if you want me to close this issue, or leave it open - Let me know if you need me to close it

**Comment by reZach** [comment]
@netpoetica Keep it open please, that way I know there is [future] work to do here.
Thanks again!

**Comment by Turtus** [comment]
any updates? trying to upgrade to electron 15 - and its not so easy - maybe you have done some part already

**Comment by reZach** [comment]
@Turtus I actually tried a day before you posted your comment. There's an issue with Electron V14, but I haven't drilled down further into it yet.

**Comment by Turtus** [comment]
me too ( for now i`m installed clean electron 15 and trying to move thing i need feo secure template... new with electron js so maybe later i will ask for your review, if it possible )))

**Comment by reZach** [comment]
@Turtus it looks like the upgrade is failing due to the `additionalArguments` I'm using for the **store** module within this template. I've [opened an issue](https://github.com/electron/electron/issues/32064) at the electron repo.

**Comment by reZach** [comment]
@Turtus / @netpoetica the [latest version](https://github.com/reZach/secure-electron-template/releases/tag/v17.0.0) of this template will fix this issue. Please re-open this issue if you encounter any problems.
