### ISSUE TITLE
Looking for Electron Developer

### ISSUE THREAD

**Issue by nolandubeau** [reZach/secure-electron-template#72]
Hi, this isn't an issue but I couldn't find any other way to contact you.  I love the work you have done on this template.  Thank you for open sourcing it.  I am looking for an experience electron / react developer and was wondering if you would be interested.  The project would benefit from using these best practices. Hope you hear from you and thanks again. Nolan.

**Comment by reZach** [comment]
Hi @nolandubeau thanks for reaching out.

Thank you for your offer, but I am not looking for another opportunity at this time. Of course, you are free to use this template and ask questions and I'll do my best to help in my spare time.
