### ISSUE TITLE
[Question] How can I import assets dynamically?

### ISSUE THREAD

**Issue by Math-42** [reZach/secure-electron-template#74]
How can I import aseets dynamically from the resources folder? like images and audios? it would be great if the template gave an example about it.

An example of what I mean:
```
export default function DivWithImage(props) {
    return (
      <div>
        <img src={props.src} />
      </div>
    )
}
```

**Comment by reZach** [comment]
@Math-42 You'll probably have to [dynamically import](https://stackoverflow.com/a/53777456/1837080) the image in your `DivWithImage` method. You should be able to reference the source of the image if you stick your images in the [resource directory](https://github.com/reZach/secure-electron-template/tree/master/resources).

**Comment by reZach** [comment]
@Math-42 I'm assuming you figured this out? I'm going to close out this issue if I don't hear any update in a week.

**Comment by Math-42** [comment]
Actually it didn't work, can't find the asset in the resources folder

**Comment by reZach** [comment]
@Math-42 note that [extraFiles](https://www.electron.build/configuration/contents#extrafiles) can be used, and is used in the [template today](https://github.com/reZach/secure-electron-template/blob/master/package.json#L29). Might point you in the right direction.

**Comment by reZach** [comment]
@Math-42 I'm going to close this as I haven't heard any update in a number of months. Please re-open this if you continue to investigate this feature you are adding.
