### ISSUE TITLE
Move To/Rewrite Using Permissive License

### ISSUE THREAD

**Issue by tERyceNzAchE** [reZach/secure-electron-template#75]
The currently used GPL means that any applications based on this great template must also release their source code.  This severely limits its use.

Please move to a more permissive license, such as MIT or BSD.

**Comment by reZach** [comment]
@tERyceNzAchE I understand, but the [author of the code](https://github.com/reZach/secure-electron-template/issues/39#issuecomment-726956924) has set that license. You can try to speak with him if he considers changing it.

**Comment by tERyceNzAchE** [comment]
@reZach, sorry it wasn't clear this repo was a fork of another.

**Comment by reZach** [comment]
@tERyceNzAchE Not a problem. This isn't a strict fork but there _is_ code from @moloch-- in this repo with is GPL licensed.

**Comment by reZach** [comment]
@tERyceNzAchE the template [is now MIT](https://github.com/reZach/secure-electron-template/releases/tag/v10.0.0).

**Comment by tERyceNzAchE** [comment]
Thank you @reZach! Did you get permission to relicense the GPL code?

**Comment by reZach** [comment]
@tERyceNzAchE Please see the [linked comment](https://github.com/moloch--/reasonably-secure-electron/issues/3#issuecomment-824329630).
