### ISSUE TITLE
Securing the source code

### ISSUE THREAD

**Issue by kzolti** [reZach/secure-electron-template#79]
I ran the "npm run dist-linux" command. 
In the created file, "app.asar/app/src" contains the contains the unprotected source code, removing this will not cause a problem with the application. The app is probably working with the contents of the "app.asar/app/dist" folder.

**Comment by reZach** [comment]
@kzolti great suggestion, please see [the latest release](https://github.com/reZach/secure-electron-template/releases/tag/v11.0.0) for these changes. Please re-open if you have further questions, but I'm not seeing any /src folders/files in the asar.

The other folders, `dist`, `electron` and `localization` need to be included or the app breaks.
