### ISSUE TITLE
Updating and license provisioning

### ISSUE THREAD

**Issue by KevinBatdorf** [reZach/secure-electron-template#80]
Hi, I'm new to Electron.

Can you detail a bit more how updating would work, and how licensing in general works?

~My assumption is that currently there is no updating mechanism implemented. Is that right?~ ([Was wrong about this assumption](https://www.electron.build/))

For licensing, my assumption is that you need to somehow provision a license for a user at build time so that you can include the key file in the distribution files. Is that accurate? That doesn't seem very practical. If so, could you explain a reasonable workflow?

Thanks

**Comment by reZach** [comment]
Hi @KevinBatdorf, yes that is the current flow. I have not yet thought of a more-reasonable workflow for licensing. My main challenge I was working to overcome was to provide a free mechanism for licensing and did not think much about a release workflow. 

Is there a use case you are in need of that would benefit others who may share the same desire as yourself?

**Comment by KevinBatdorf** [comment]
If you provision a license at build for a user, you wouldn't be able to _auto_ update the application for them ever, right? Since pushing an update would go out to everyone and wouldn't be unique any longer. Is that right?

Could you possibly provision say 1000 license keys during a build? Then if you sell them all, distribute another 1000 in an update release that also includes the original 1000 keys (so existing users aren't affected). Does that make sense?

**Comment by rshea0** [comment]
Yeah baking the license key into the build seems like a bad idea.

Would be better to have a single public/private keypair. Bake the public key into the app and generate license key files signed by the private key. Then you just need to generate new licences.

**Comment by reZach** [comment]
Thanks @KevinBatdorf / @rshea0 for your discussion.

The original intent of [secure-electron-license-keys](https://github.com/reZach/secure-electron-license-keys) was to provide _offline_ support for license keys in an Electron app. However, it appears you both want to use [electron-builder](https://www.electron.build/) (which this template uses) for an auto-update scenario.

If you are looking for an out of the box solution, I've _heard of_, but not used before, [keygen](https://keygen.sh/integrate/). This doesn't use the licensing mechanism in this project, but may provide your use case. I do believe this is a paid solution.
If you want to continue to use the licensing mechanism already included in this template with electron-builder, I'd recommend if either of you would ask the question on their (electron-builder) repo. I feel that you'd be able to host for yourselves some store of license keys or similar, and then configure the auto-updater to _exclude_ overwriting license data within the app and/or update licenses on a per-user basis. 

Let me know your thoughts but that is what I think is the next best step in this conversation.

**Comment by rshea0** [comment]
I see. The repo should probably explain that intent more clearly. It took me a while just to figure out how it was meant to be used.

**Comment by KevinBatdorf** [comment]
I like the idea of offline licensing but it's not really practical to assume your app would never have an update that your users wouldn't be interested in. One alternative strategy would be to keep a mailing list I suppose and notify users that way. That's about 3 extra steps for the user though.

> I feel that you'd be able to host for yourselves some store of license keys

This makes sense actually and might be trivial to set up. I'll dive in this Sunday and check out how it all works.

I'll check on solutions and if I get that far I'll report back.

**Comment by reZach** [comment]
Any update @KevinBatdorf?

I can update that repo @rshea0 to more clearly explain the intent and currently supported functionality of it.

**Comment by KevinBatdorf** [comment]
I didn't see a way to distribute an update without replacing the entire thing. There may be a way but I didn't really investigate too deeply. I'm just planning to prototype for now anyway and figure out the licensing another day.

**Comment by reZach** [comment]
I'm going to close this issue @KevinBatdorf unless you have more information you'd like to bring back and restart the conversation.
