### ISSUE TITLE
Mistakes were made in the french translations

### ISSUE THREAD

**Issue by JeffSilverface** [reZach/secure-electron-template#81]
here is the file with the corrections.

{
  "Hello": "Bonjour",
  "File": "Fichier",
  "Exit": "Quitter",
  "Edit": "Éditer",
  "Undo": "Annuler",
  "Redo": "Rétablir",
  "Cut": "Couper",
  "Copy": "Copier",
  "Paste": "Coller",
  "Delete": "Effacer",
  "Select All": "Tout sélectionner",
  "View": "Vue",
  "Reload": "Recharger",
  "Force Reload": "Rechargement forcé",
  "Toggle Developer Tools": "Outils de développement",
  "Reset Zoom": "Réinitialiser le zoom",
  "Zoom In": "Agrandir",
  "Zoom Out": "Réduire",
  "Toggle Fullscreen": "Basculer en plein écran",
  "Language": "Langue",
  "Window": "Fenêtre",
  "Minimize": "Minimiser",
  "Zoom": "Zoom",
  "Close": "Fermer",
  "Help": "Aide",
  "Learn More": "En apprendre plus"
}

**Comment by reZach** [comment]
Thanks for opening this @JeffSilverface, I've pushed out new changes in [this release](https://github.com/reZach/secure-electron-template/releases/tag/v12.0.0).
