### ISSUE TITLE
Hi! I've seen that you are an expert in Electron, could you help my in this question?

### ISSUE THREAD

**Issue by lucaslgr** [reZach/secure-electron-template#82]
My question was posted in Stack Over Flow, thanks in advance!
https://stackoverflow.com/questions/67811787/my-window-in-electron-doesnt-appear-no-matter-what-i-do-there-is-something-wro

**Comment by reZach** [comment]
Hi @lucaslgr, it seems you have some responses to your question, have you been able to answer your question?

**Comment by lucaslgr** [comment]
Hi @reZach not yet, I've tried what they suggested for me, but nothing works.

**Comment by reZach** [comment]
I can't guarantee, but if you post a new git repository with the problem I'll try to give it a shot and look at it.

**Comment by reZach** [comment]
This isn't related to this repository though, so I will close this issue and if you post a git repo to look at, I'll try to look at it.
