### ISSUE TITLE
Download remote files

### ISSUE THREAD

**Issue by eramudeep** [reZach/secure-electron-template#83]
**MacOs: 11.4 (20F71)**:  
**Version : 12.0.0**:

I am trying to download the Remote File, But its Blocking the URL
<img width="1344" alt="Screenshot 2021-06-12 at 11 57 49 AM" src="https://user-images.githubusercontent.com/38516686/121767368-6a4d6000-cb75-11eb-9cb9-5006ab9666c4.png">

**My Code**: `win = new BrowserWindow({
    width: 800,
    height: 600,
    title: "Legitquest is currently initializing...",
    webPreferences: {
      devTools: isDev,
      webSecurity:false,
      nodeIntegration: false,
      nodeIntegrationInWorker: false,
      nodeIntegrationInSubFrames: false,
      contextIsolation: true,
      enableRemoteModule: false,
      additionalArguments: [`storePath:${app.getPath("userData")}`],
      preload: path.join(__dirname, "preload.js"), /* eng-disable PRELOAD_JS_CHECK */
      disableBlinkFeatures: "Auxclick"
    }
  });`

**IN Main** 
`win.webContents.session.on('will-download',(event, item, webContents) =>{
    console.log("event, item, webContents",event, item, webContents);
  })`

In View => 
`<a 
                  href="https://main.sci.gov.in/jonew/judis/36402.pdf"   
                  name={"download-button"}
                  style={{ cursor: "pointer" }} 
                 >
                  <i className="fa fa-print" /> Download From Court Website
                </a>`

Need Help. Thank you !!

**Comment by reZach** [comment]
@eramudeep you have to add https://main.sci.gov.in to `validOrigins` either in the `will-navigate` or `will-redirect` bindings in **main.js**. I'll move up a change differentiating the error message since I see these are both the same. This should unblock you.

**Comment by reZach** [comment]
@eramudeep I assume my suggestion worked for your use case?

**Comment by reZach** [comment]
Please re-open if you continue to experience an issue @eramudeep.
