### ISSUE TITLE
rpi4 Timeout exceeded. For async tests and hooks

### ISSUE THREAD

**Issue by grandixximo** [reZach/secure-electron-template#84]
**Operating system**:  raspbian
**Version of the template**: 12.1.0

I've tried to run npm test on a raspberry pi 4, the window opens up, on top it states Application is currently initializing.... but the window it's all white, and in the console I get this error

`> secure-electron-template@12.1.0 test /home/pi/secure-electron
> mocha

  Application launch
    1) "before each" hook for "shows an initial window"

  0 passing (2m)
  1 failing

  1) Application launch
       "before each" hook for "shows an initial window":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/pi/secure-electron/test/spec.js)
      at createTimeoutError (node_modules/_mocha@8.4.0@mocha/lib/errors.js:498:15)
      at Hook.Runnable._timeoutError (node_modules/_mocha@8.4.0@mocha/lib/runnable.js:431:10)
      at Timeout.<anonymous> (node_modules/_mocha@8.4.0@mocha/lib/runnable.js:246:24)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)`

I tried to extend the timer to 100000, still getting same error.

**Comment by reZach** [comment]
Not sure if it's the speed of the processor that's causing it to timeout like this.

**Comment by grandixximo** [comment]
No it's not, I was able to build an older app with electron using the instructions here

https://www.beekeeperstudio.io/blog/electron-apps-for-arm-and-raspberry-pi

I've given up on this template, and I'm running insecure for now....

**Comment by reZach** [comment]
Spectron is [going to be deprecated](https://github.com/electron-userland/spectron/issues/1045), we'll move to another test framework. I'm going to close this as I won't support Spectron due to this.
