### ISSUE TITLE
Error while installing modules with npm

### ISSUE THREAD

**Issue by steledama** [reZach/secure-electron-template#86]
First of all congratulations for the project which I consider very useful and interesting.
When i try to install npm modules at the end i receive an error (see logs attached).
Any help would be appreciated. thanks
[2021-06-29T19_18_13_493Z-debug.log](https://github.com/reZach/secure-electron-template/files/6735884/2021-06-29T19_18_13_493Z-debug.log)

**Comment by reZach** [comment]
@steledama what command did you use to try to install?

**Comment by steledama** [comment]
npm i

**Comment by reZach** [comment]
@steledama I'd recommend you try a combination of these things. I have not been able to replicate but perhaps one of these options can help you.

1. Clear the npm cache (`npm cache clean --force`).
2. Delete the **package-lock.json** file.
3. Try [installing a previous version of npm](https://stackoverflow.com/a/68327786/1837080) (optional).
4. And then try installing npm packages again (`npm i`).

**Comment by steledama** [comment]
First of all really thank you for the feedback and service you are doing to the community.

I decided to switch development platforms and switched to linux. I don't have that problem anymore and I'm starting to study.

I am making radical changes to the project. I will use your work and give you feedback in order to help super novices like me who are not familiar with the advanced tools you make available in your project (react, redux, translation, store etc. ..)

**Comment by reZach** [comment]
Thank you for your kind words @steledama! That sounds good - keep me in the loop.
