### ISSUE TITLE
newtoelectron.md doesn't show how to send data from Main to the Embedded Web App

### ISSUE THREAD

**Issue by harlankoehn** [reZach/secure-electron-template#87]
As near as I can tell, you don't show any example of how to communicate from main.js back to the web app via the preload.js file. Am I missing something?

**Comment by WHellhaus** [comment]
In the [IPC example](https://github.com/reZach/secure-electron-template/blob/master/docs/newtoelectron.md#show-me-an-example-of-how-to-use-ipc-to-use-a-node-module) under the **index.html** file you can see where data is sent or received on the renderer end. Messages are sent by IPC using the context bridge _api_ that was made in **preload.js**. On the renderer (web app) side this is done by using _window.api.send('channel_name')_ and data is sent back from the main side with _win.webContents.send('channel_name')_. Then the renderer can use _window.api.receive('channel_name')_ to get that data on the renderer side.

**Comment by reZach** [comment]
Thank you for providing feedback @WHellhaus. @harlankoehn does this page WHellhaus linked to answer your question?

**Comment by reZach** [comment]
I'm closing this and can re-open if necessary.
