### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by tyler-hitzeman** [reZach/secure-electron-template#88]
Opening issue because I couldn't find other contact info. 

Just wanted to say THANK YOU for putting together this template! I've spent 8 full days trying out the popular boilerplates and running into roadblocks. It took me 1 hour to get this up-and-running. I love how it  "just works," but also has sensible defaults and security out-of-the-box. It's clear that this was put together by someone who has shipped & maintained a real electron app. 

Thanks again.

PS. You should consider adding a sponsor link so others who get massive benefit from this can support your work.

**Comment by reZach** [comment]
Thank you _kindly_ for your words @tyler-hitzeman! I really appreciate your message. I too found it frustrating, and the lack of secure templates when I began this so I'm very glad you/others can start off on a faster foot! As much as extra income would be nice, getting paid to make these changes wouldn't motivate me to make them (ie. getting paid for a hobby becomes a job) - so to that I say enjoy it for free!

I want to ask though how can we reduce the 1hr down to something like 5 minutes? Were there hiccups in getting started that can be removed for easier adoption?

**Comment by tyler-hitzeman** [comment]
Gotcha. The hour was spent trying to get things setup with typescript using [this suggestion](https://github.com/reZach/secure-electron-template/issues/47#issuecomment-811245733) from #47 

I tried copying his branch exactly, but wasn't successful. I gave up and am not using Typescript because I didn't want to spend the extra time

**Comment by reZach** [comment]
Better late than never, thank you for your suggestion @tyler-hitzeman. This repo is now sponsor-able (and I do have partial typescript built in now as well). Thanks and have a good day!
