### ISSUE TITLE
What are the best practices to implement user authentication and page

### ISSUE THREAD

**Issue by isaacbizteg** [reZach/secure-electron-template#90]
Hi @reZach , thanks for the awesome project.

I would like to learn more about building app with electronjs, I'm currently using python.

I have successfully play with some of the features in this app and it works 100% as expected and I would like to share some screenshots below.

Base language in English with sidebar 😄 
![image](https://user-images.githubusercontent.com/82525506/127655279-17a15d09-2b8d-4476-8f18-a504caf8c027.png)

Translation to Chinese 😄 
![image](https://user-images.githubusercontent.com/82525506/127655640-95730509-407d-49e6-956b-4d4e0f5dfd1e.png)

Also I would like to further improve the current situation to include more features, my questions are basically around ipc as it is new to me: 

1. How do I securely calling API and does it relates to ipc implementation? I'm familiar with axios but with ipc in place do I have to do it differently?

2. I would like to restrict pages only for authenticated users, do I store the authenticated user's token as normal or in ipc?

Additionally, I have tried to implement a login/register page following the guide from this link https://www.bezkoder.com/react-redux-jwt-auth/ but it uses additional actions and services folder for the auth instead of ipcMain/ipcRenderer. So is this practice correct?

Hope I'm not bothering too much of your time. Thank you 😄

**Comment by reZach** [comment]
Thanks @isaacbizteg! It seems like you solved your question, if it is helpful to others, you may post your solution to guide others who may have the same question as you did.
