### ISSUE TITLE
Unable to use TailwindCSS framework

### ISSUE THREAD

**Issue by daxidngyn** [reZach/secure-electron-template#92]
Is there currently a way to get tailwindcss to work with this template? I've tried following this [guide](https://rodpadev.medium.com/add-tailwind-css-to-the-popular-electron-react-boilerplate-erb-f1286b5b04f) as well as the one on tailwindcss's site but to no avail.

**Comment by reZach** [comment]
Hi @daxidngyn. I have not explored how to implement tailwindcss into this template. Have you had any further luck since first posting your comment?

**Comment by daxidngyn** [comment]
Pretty much have given up as I've followed multiple guides but have had no success

**Comment by reZach** [comment]
Helllo @daxidngyn. I am currently working on an ultimate electron js guide and in it, going to configure TailwindCSS into Electron. The post is still being written, but you may check out my blog (where the post will be written), or subscribe to get the notification when I post it.

https://www.debugandrelease.com/

**Comment by reZach** [comment]
Much delayed, but I hope this leads you to what you were looking for, @daxidngyn.
https://www.debugandrelease.com/how-to-use-tailwindcss-with-electron/
