### ISSUE TITLE
POST method API for local network

### ISSUE THREAD

**Issue by isaacbizteg** [reZach/secure-electron-template#93]
Hi, may I ask. 

My electronjs app is running on the local IP address 192.168.0.111 port 40992. I have another app wish to call the API `http://192.168.0.111:40992/getUserlist` from this electronjs app. I tried but it is not working, may I know am I doing it correctly?

Thanks in advance.

**Comment by reZach** [comment]
Hi @isaacbizteg are you seeing any messages in the logs?

**Comment by isaacbizteg** [comment]
Hi @reZach, sorry I am new to electronjs and a bit confuse with nodejs implementation altogether. 

However in the end I am able to make it work using nodejs as the API server. 

I initiate the http.createServer().listen(3000) and I have to call it via http://192.168.0.111:3000/getUserlist even if the electronjs is running on http://192.168.0.111:40992. So how it works is the API will pick up by the main.js via ipcMain and then using win.sendContents.send back to ipcRenderer to the user interface for result/output.
