### ISSUE TITLE
Tests was failed

### ISSUE THREAD

**Issue by NewEXE** [reZach/secure-electron-template#95]
**Operating system**:  Windows 11 Pro 10.0.22000 (latest for now)
**Version of the template**: 13.1.0 (latest for now). Installed from "master" branch
**NPM version**: 8.1.0

First of all, thanks for probably the best electron boilerplate, and espessially for FAQ and novice's guide. Once maybe my prooject deserves a place in yourapps.md ;)

But regardlesss of aplication's successfully run (`npm i && npm run dev`), here is a problen on `npm run test`:

```
 $ npm run test

> secure-electron-template@14.0.0 test
> mocha

  Application launch
    1) "before each" hook for "shows an initial window"

  0 passing (10s)
  1 failing

  1) Application launch
       "before each" hook for "shows an initial window":
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\Vlad\Documents\Projects\secure-elec
tron-template\test\spec.js)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

```

What might be the problem? Tnanks.

It's seems like problems in my setup (or OS), but unfortunately Windows is fitst-target platform for my app, so I must use it

**Comment by reZach** [comment]
Spectron is [going to be deprecated](https://github.com/electron-userland/spectron/issues/1045), we'll move to another test framework. I'm going to close this as I won't support Spectron due to this. For the time being, you can un-comment out the test scenarios for your template.
