### ISSUE TITLE
[Request] typescript version

### ISSUE THREAD

**Issue by DiegoFleitas** [reZach/secure-electron-template#97]
**Is your feature request related to a problem? Please describe.**
Electron showcases now a [typescript quickstart](https://github.com/electron/electron-quick-start-typescript) but we don't have a secure version yet

**Describe the solution you'd like**
I think It would be great to have a secure electron template with typescript. Since typescript is being used so much nowdays.

**Describe alternatives you've considered**
I think the alternative would be doing it myself. Which I will attempt but doubt my own ability to do it without weird hacks

**Additional context**
Typescript is the 4th most used language today as of GitHub trends
![imagen](https://user-images.githubusercontent.com/15369935/141667836-bda73622-e827-49c3-a8d1-2b725d2e66a9.png)

**Comment by NewEXE** [comment]
As for me, it will be good to have ts version of this useful carcase.

_Some information about typescript integration avalable in [FAQ](https://github.com/reZach/secure-electron-template/blob/master/docs/faq.md#can-i-use-typescript-with-this-template)_

**Comment by reZach** [comment]
@DiegoFleitas For the time being, you can use [this pull request](https://github.com/tyler-hitzeman/secure-electron-template-ts/pull/1) as a starting point for updating the template with Typescript. My next priority for this template is to fully enable sandbox mode and upgrade to the latest version of Electron which will take some time. I am hoping this other user's previous work can get you started in the meantime!

**Comment by reZach** [comment]
@DiegoFleitas / @NewEXE - This template now has [partial Typescript support](https://github.com/reZach/secure-electron-template/releases/tag/v18.0.0) (only in the app/src folder)!
